# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  admin.category:
          class: AppBundle\Admin\CategoryAdmin
          arguments: [~, AppBundle\Entity\Category, ~]
          tags:
              - { name: sonata.admin, manager_type: orm, label: Category }
  admin.product:
          class: AppBundle\Admin\ProductAdmin
          arguments: [~, AppBundle\Entity\Product, ~]
          tags:
            - { name: sonata.admin, manager_type: orm, label: Product }
  admin.subcategory:
          class: AppBundle\Admin\SubcategoryAdmin
          arguments: [~, AppBundle\Entity\Subcategory, ~]
          tags:
            - { name: sonata.admin, manager_type: orm, label: Subcategory }